#@data/values
---
system_domain: ""
system_namespace: ""

images:
  metric_proxy: "oratos/metric-proxy@sha256:d64fd88c9c843534c75b8e574edc73a6648497f73336506a50038a2a7d09d801"

metric_proxy:
  ca:
    secret_name: "metric-proxy-ca"
    crt: "" #! Base64-encoded ca for the metric-proxy-ca
    key: "" #! Base64-encoded private key for the cert above
  cert:
    secret_name: "metric-proxy-cert"
    crt: "" #! Base64-encoded cert for the metric-proxy server requires CN of metric-proxy
    key: "" #! Base64-encoded private key for the cert above

