#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-proxy
  namespace: #@ data.values.system_namespace
  labels:
    app: metric-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metric-proxy
  template:
    metadata:
      labels:
        app: metric-proxy
    spec:
      serviceAccountName: metric-proxy
      containers:
      - name: cf-auth-proxy
        image: #@ data.values.images.cf_auth_proxy
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: LOG_CACHE_GATEWAY_ADDR
            value: https://localhost:8081
          - name: CAPI_ADDR
            value: #@ "http://capi.{}.svc.cluster.local:80".format(data.values.system_namespace)
          - name: UAA_ADDR
            value: #@ "http://uaa.{}.svc.cluster.local:8080".format(data.values.system_namespace)
          - name: UAA_CLIENT_ID
            value: #@ data.values.client.id
          - name: UAA_CLIENT_SECRET
            value: #@ data.values.client.secret
        volumeMounts:
          - mountPath: /ca
            name: ca
            readOnly: true
          - mountPath: /metrics-certs
            name: metrics-certs
            readOnly: true
      - name: metric-proxy
        image: #@ data.values.images.metric_proxy
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: ADDR
          value: :8081
        - name: APP_SELECTOR
          value: cloudfoundry.org/app_guid
        - name: NAMESPACE
          value: cf-workloads
        - name: QUERY_TIMEOUT
          value: "5"
        - name: CA_PATH
          value: /ca/tls.crt
        - name: CERT_PATH
          value: /metric-proxy-certs/tls.crt
        - name: KEY_PATH
          value: /metric-proxy-certs/tls.key
        volumeMounts:
        - mountPath: /ca
          name: ca
          readOnly: true
        - mountPath: /metric-proxy-certs
          name: metric-proxy-certs
          readOnly: true
      volumes:
      - name: ca
        secret:
          secretName: #@ data.values.metric_proxy.ca.secret_name
      - name: metric-proxy-certs
        secret:
          secretName: #@ data.values.metric_proxy.cert.secret_name
      - name: metrics-certs
        secret:
          secretName: log-cache-metrics
